sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - mvn clean install -Dwebtests.verbose=true -Dwebtests.video.enabled=true -Dwebtests.video.dir=$PWD/web/target/videos

# Skip install step which is not needed with maven
install: true

cache:
 directories:
 - $HOME/.m2

jdk:
  - oraclejdk8
