version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:erbium

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .

  webtests:
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:1.14-browsers
    environment:
      DISPLAY: :99

    steps:
      - run: sudo Xvfb :99 -screen 0 1920x1200x24 > /dev/null 2>&1 &
      - attach_workspace:
          at: ~/repo
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
            ps -efa | grep Xvfb
          name: Check install
      - run: export DISPLAY=:99 && mvn clean install
      - store_artifacts:
          path: ~/repo/core/target/surefire-reports
      - store_artifacts:
          path: ~/repo/core/target/webtests-videos

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^gh-pages$/
      - webtests:
          requires:
            - build
