version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.1

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      DISPLAY: :99

    steps:
      - run: sudo Xvfb :99 -screen 0 1920x1200x24 > /dev/null 2>&1 &
      - attach_workspace:
          at: ~/repo
      - browser-tools/install-chrome
      - browser-tools/install-firefox
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            firefox --version
            chromedriver --version
            ps -efa | grep Xvfb
          name: Check install
      - run: export DISPLAY=:99 && mvn clean install
      - store_artifacts:
          path: ~/repo/target/surefire-reports
      - store_artifacts:
          path: ~/repo/target/webtests-videos

workflows:
  build:
    jobs:
      - build
